#!/usr/bin/ruby

# take a logfile and outputs daily clicks as csv (for processing with spreadsheet program)

f = File.open(ARGV[0])
days = {}
while f.gets
   if $_.index("Processing ")==0
        splitted = $_.split
        action = splitted[1]
        date  = splitted[5]
        if days[date].nil? then
          days[date] = 1
        else
          days[date] += 1
        end
   end
end

days_array = days.to_a
days_array.sort! {|d1, d2| d1[0] <=> d2[0]}
days_array.each do |d|
  puts "#{d[0]} , #{d[1]}"
end