#!/bin/bash
# specific parameters
USERNAME=communtu
DIST=lucid
VER=10.04
RELEASE=$1

if [ $# != 1 ]; then
     echo "Usage:"  1>&2
     echo "remaster-isos <release>"  1>&2
     exit 1
fi

if [[ $EUID -ne 0 ]]; then
     echo "This script must be run as root" 1>&2
     exit 1
fi

# propagate errors
set -e

cd /home/${USERNAME}/livecd/isos
wget http://cdimage.ubuntu.com/releases/${DIST}/${RELEASE}/${DIST}-desktop-i386.iso -O ubuntu-${VER}-desktop-i386.iso
wget http://cdimage.ubuntu.com/releases/${DIST}/${RELEASE}/${DIST}-desktop-amd64.iso -O ubuntu-${VER}-desktop-i386.iso
wget http://cdimage.ubuntu.com/kubuntu/releases/${DIST}/${RELEASE}/${DIST}-desktop-i386.iso -O kubuntu-${VER}-desktop-i386.iso
wget http://cdimage.ubuntu.com/kubuntu/releases/${DIST}/${RELEASE}/${DIST}-desktop-amd64.iso -O kubuntu-${VER}-desktop-i386.iso
wget http://cdimage.ubuntu.com/xubuntu/releases/${DIST}/${RELEASE}/${DIST}-desktop-i386.iso -O xubuntu-${VER}-desktop-i386.iso
wget http://cdimage.ubuntu.com/xubuntu/releases/${DIST}/${RELEASE}/${DIST}-desktop-amd64.iso -O xubuntu-${VER}-desktop-amd64.iso

for i in kubuntu-${VER}-desktop-amd64 kubuntu-${VER}-desktop-i386 ubuntu-${VER}-desktop-amd64 ubuntu-${VER}-desktop-i386 xubuntu-${VER}-desktop-amd64 xubuntu-${VER}-desktop-i386
  do /home/${USERNAME}/web2.0/communtu-program/script/remaster setup-kvm $i
done
