#!/bin/bash
sed -i 's/:message_\([0-9]*\), :scope => \[:txt, :\([a-zA-Z_]*\), :\([a-zA-Z_]*\), :\([a-zA-Z_]*\)\]/:\2_\3_\4_\1/g' $1
sed -i 's/:message_\([0-9]*\), :scope => \[:txt, :\([a-zA-Z_]*\), :\([a-zA-Z_]*\)\]/:\2_\3_\1/g' $1