#! /bin/bash
############################
# Author: Timo Denissen    #
# E-Mail: timo@communtu.de #
# Version: 1.0             #
############################

locales_folder=config/locales
source_lang=$1
dest_lang=$2
yml_file=$locales_folder/template-$source_lang.yml
pot_file=$locales_folder/template-$dest_lang.pot
po_file=$locales_folder/template-$dest_lang.po

# Checking number of arguments
if [ $# -lt 2 ]; then
    echo "Usage: "
    exit 1
fi

if [ $source_lang = 'de' ]; then
    yml_file=$locales_folder/template.yml
else
    yml_file=$locales_folder/template-$dest_lang.yml
fi

# Adding new language
touch $pot_file
script/yaml2po $source_lang $yml_file $pot_file
cp $pot_file $po_file
echo "Finish"
