#!/usr/bin/ruby
# (c) 2008-2011 by Allgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.

#script shows which description var has
#script/bundle_translate Uebersetzen en name
#system 'script/bundle_translate Uebersetzen en' von console
var = (ARGV[0])
if (ARGV[2]) == "name"
  f = File.open('/home/communtu/web2.0/communtu-test/config/locales/bundle-names.po')
else
  f = File.open('/home/communtu/web2.0/communtu-test/config/locales/bundles.po')
end
 while not f.eof? do
  german = ""
  english = ""
   while(!f.eof? && (line = f.gets)[var]=="#{var}") do
   german << f.gets
   english << f.gets
#output
   german = german.gsub("msgid \"", "")
   german = german.gsub("msgstr \"", "")
   german = german.gsub("\n", "")
   german = german.gsub("\"", "")
   english = english.gsub("msgstr \"", "")
   english = english.gsub("msgstr", "")
   english = english.gsub("\n", "")
   english = english.gsub("\"", "")   
if (ARGV[1]) == "en"
  print english   
else
  print german
end
   end
 end
