#!/bin/bash
############################
# Author: Timo Denissen    #
# E-Mail: timo@communtu.de #
# Version: 2.1             #
############################
# (c) 2008-2011 by Allgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.

default=en
language=$1
poedit=$2

script/yaml2po $default config/locales/template-en.yml config/locales/template-$language.pot
if [ $poedit = 1 ]
then 
  if [ -f config/locales/template-$language.po ]
  then poedit config/locales/template-$language.po
  else cp config/locales/template-$language.pot config/locales/template-$language.po ; poedit config/locales/template-$language.po
  fi
else exit
fi
exit