#!/bin/bash
# (c) 2008-2011 by Allgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.


# copy all icon files to one location
for d in `cat app-icon-dirs`
  do echo "copying "$d
  cp $d/* ../public/images/apps/
done


# convert all icon file to browser-compatible format
cd ../public/images/apps
for f in *.xpm *.ico *.tif *.tiff *.svg
  do echo "converting "$f" to "$f.png
   convert $f $f.png
done
rm *.xpm *.ico *.tif *.tiff *.svg
