#!/bin/bash

# copy all icon files to one location
for d in `cat app-icon-dirs`
  do echo "copying "$d
  cp $d/* ../public/images/apps/
done


# convert all icon file to browser-compatible format
cd ../public/images/apps
for f in *.xpm *.ico *.tif *.tiff *.svg
  do echo "converting "$f" to "$f.png
   convert $f $f.png
done
rm *.xpm *.ico *.tif *.tiff *.svg
