#!/bin/bash
cd ..
echo "download database from webserver"
scp communtu@communtu.de:/home/communtu/web2.0/db.backup.gz .
echo "update your local database"
gunzip -c db.backup.gz | mysql -u root -p communtu
echo "delete the gz file"
sleep 5s
rm db.backup.gz