#!/bin/bash
# check for debs that are empty (i.e. contains no dependencies)

# (c) 2008-2011 byllgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.


cd `dirname "$0"`/..
base=$(pwd)
for d in public/debs/pool/*/*/*/*all-all*deb
  do tmp=$(mktemp -d)
     pushd $tmp > /dev/null
     dpkg -e $base/$d
     grep -q Depends DEBIAN/control 2> /dev/null
     if [ $? -ne 0 ]
     then
       echo $d
     fi
     popd > /dev/null
     rm -rf $tmp
done