#!/bin/bash
# script for installing rails and commutu
# use a non-blank argument to the script if you are a developer with access to the communtu.org server
developer=$1

#adapt to your local settings, if needed
dbuser=root

# (c) 2008-2011 by Allgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.

set -x
# git
sudo apt-get install -y git-core
# translating
sudo apt-get install -y poedit python-yaml
# rails
sudo apt-get install -y ruby rdoc irb libyaml-ruby libzlib-ruby ri libopenssl-ruby sqlite3 libsqlite3-ruby rubygems mongrel
# gem 1.3.6
sudo add-apt-repository ppa:johnf-inodes/rubygems
sudo apt-get update
sudo apt-get install -y rubygems
sudo ln -s /usr/bin/gem1.8 /usr/bin/gem
sudo ln -s /var/lib/gems/1.8/bin/rake /usr/bin/
sudo gem install -v=2.2.2 rails
sudo gem install i18n
sudo sed -i "s/deprecate :/# deprecate :/" /var/lib/gems/1.8/gems/rails-2.2.2/lib/rails_generator/secret_key_generator.rb
# needed for backgroundrb
sudo gem install chronic packet
# mysql server
sudo apt-get install -y mysql-server libmysql-ruby ruby1.8-dev libmysqlclient15-dev
pwdpath=$(pwd)
if [ ${pwdpath##*/} != "communtu" ]; then
  if [ $dev == "" ]; then
    # read-only version
    git clone git://github.com/communtu/communtu.git
  else  
    # developers version
    git clone git@github.com:communtu/communtu.git
  fi  
  cd communtu
fi
# setting up rails config
cp config/database.yml.template config/database.yml
# setup database
set +x
res=1
while [ $res -ne 0 ]
  do
    echo -n "enter database password:"
    read -s passwd
    echo
    echo "dropping and then re-creating communtu database"
    mysqladmin -u $dbuser --password=$passwd drop communtu
    mysqladmin -u $dbuser --password=$passwd create communtu
    res=$?
  done  
echo
sed -i "s/password:/password: $passwd/" config/database.yml
sed -i "s/root/$dbuser/" config/database.yml
set -x
  if [ $dev == "" ]; then
    # test database
    rake db:load RAILS_ENV=production # production mode is faster; production and development dbs are the same
  else
    # database from communtu.org
    script/database $passwd
  fi    
mkdir log

set +x
echo
echo "now try:"
echo "script/server"
echo "script/console"
