#!/usr/bin/ruby

# take a logfile and outputs daily clicks as csv (for processing with spreadsheet program)

# (c) 2008-2011 by Allgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.


f = File.open(ARGV[0])
days = {}
while f.gets
   if $_.index("Processing ")==0
        splitted = $_.split
        action = splitted[1]
        date  = splitted[5]
        if days[date].nil? then
          days[date] = 1
        else
          days[date] += 1
        end
   end
end

days_array = days.to_a
days_array.sort! {|d1, d2| d1[0] <=> d2[0]}
days_array.each do |d|
  puts "#{d[0]} , #{d[1]}"
end
