#!/bin/bash
cd `dirname "$0"`/..
# webalizer
script/webalizer
# kill old instances...
pkill rake
sleep 5
pkill -2 rake
sleep 5
pkill -9 rake
# synchronise repositories
script/sync_repos
# generate debian packages
script/check_debs
