#!/usr/bin/ruby

# (c) 2008-2011 byllgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.

require 'yaml.rb'

def end_of_trans(line)
  line.nil? || line=="\n" || line[0,2]=="#:"
end

if ARGV.size < 3 then
  puts "usage: po2yaml2 destination-language-code source-file target-file"
else
f = File.open(ARGV[1])
y = {}
line1 = nil
while not f.eof? do
  # look for line with tag
  # do we have one from last round?
  if !line1.nil? && line1[0,2]=="#:" then
    line = line1
  else
    while((line = f.gets)[0,2]!="#:" && !f.eof) do
    end
  end
  f.gets # original
  # skip to msgstr
  if !f.eof then
    while((trans_line = f.gets)[0,6]!="msgstr" && !f.eof) do
    end
  end
  if !trans_line.nil? then
    trans_line = trans_line[8,trans_line.size-10] # eliminate "msgstr"
    while(!end_of_trans(line1 = f.gets) && !f.eof) do
      trans_line += line1[1,line1.size-3]
    end
    if !trans_line.nil? then
      y[line[3,line.size-4]] = trans_line.gsub(/\\\"/,'"').gsub(/\\n/,"\n")
    end
  end
end
f.close

File.open(ARGV[2],"w") do |f|
  YAML::dump({ARGV[0] => y}, f)
  f.close
end

end
