#!/usr/bin/ruby
require 'yaml.rb'

def end_of_trans(line)
  line.nil? || line=="\n" || line[0,2]=="#:"
end

if ARGV.size < 2 then
  puts "usage: po2yaml2 source-file target-file"
else
f = File.open(ARGV[0])
y = {}
line1 = nil
while not f.eof? do
  # look for line with tag
  # do we have one from last round?
  if !line1.nil? && line1[0,2]=="#:" then
    line = line1
  else
    while((line = f.gets)[0,2]!="#:" && !f.eof) do
    end
  end
  f.gets # original
  # skip to msgstr
  if !f.eof then
    while((trans_line = f.gets)[0,6]!="msgstr" && !f.eof) do
    end
  end
  if !trans_line.nil? then
    trans_line = trans_line[8,trans_line.size-10] # eliminate "msgstr"
    while(!end_of_trans(line1 = f.gets) && !f.eof) do
      trans_line += line1[1,line1.size-3]
    end
    if !trans_line.nil? then
      y[line[3,line.size-4]] = trans_line.gsub(/\\\"/,'"').gsub(/\\n/,"\n")
    end
  end
end
f.close

File.open(ARGV[1],"w") do |f|
  YAML::dump({"fr" => y}, f)
  f.close
end

end