#!/usr/bin/ruby
require 'yaml.rb'
if ARGV.size < 2 then
  puts "usage: po2yaml2 source-file target-file"
else
f = File.open(ARGV[0])
y = {}
while not f.eof? do
  while((line = f.gets)[0,2]!="#:" && !f.eof) do
  end
  f.gets # original
  # skip to msgstr
  if !f.eof then
    while((trans_line = f.gets)[0,6]!="msgstr" && !f.eof) do
    end
  end
  if !trans_line.nil? then
    trans_line = trans_line[8,trans_line.size-10] # eliminate "msgstr"
    while((line1 = f.gets)!="\n" && !f.eof) do
      trans_line += line1[1,line1.size-3]
    end
    if !trans_line.nil? then
      y[line[3,line.size-4]] = trans_line.gsub(/\\\"/,'"').gsub(/\\n/,"\n")
    end
  end
end
f.close

File.open(ARGV[1],"w") do |f|
  YAML::dump({"en" => y}, f)
  f.close
end

end