#!/bin/bash
# script for installing rails3 on Ubuntu Oneiric Ocelot
# see http://blog.sudobits.com/2011/10/27/how-to-install-ruby-on-rails-in-ubuntu-11-10/

set -x
sudo apt-get install -y git curl
bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)
source .bashrc
sudo apt-get install -y build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion nodejs rubygems libopenssl-ruby libfcgi-dev sqlite3 libsqlite3-dev
rvm install 1.9.2
rvm use 1.9.2
gem install rails sqlite3

