#!/bin/bash
# script for creating a live CD from a VM image
# BEWARE: the VM image is slightly changed!!!

# are we root?
if [ `whoami` != root ]; then
  echo "This script must be run as root."
  exit 1
fi

set -e
set -x

# location of the image
VM_IMG=$1
# Ubuntu version, like 11.04
UBUNTU_VERSION=$2
# architecture: i386 or amd64
ARCHITECTURE=$3
# name of the resulting iso
OUT=$PWD/$4.iso

# mount the standard iso 
#ISO_FOLDER=/home/communtu/livecd/isos
ISO_FOLDER=/home/till/isos
ISO=$ISO_FOLDER/ubuntu-$UBUNTU_VERSION-desktop-$ARCHITECTURE.iso
ISOMOUNT=$(mktemp -d)
mount $ISO $ISOMOUNT -o loop

# extract liveCD contents
LIVECD=$(mktemp -d)
rsync -a $ISOMOUNT/ $ISOMOUNT/.disk $LIVECD --exclude filesystem.squashfs

# mount first partition of vm image
kpartx_out=$(sudo kpartx -av $VM_IMG |head -n +1)
device=/dev/mapper/$(echo $kpartx_out |cut  -d " " -f 3)
VM_MOUNT=$(mktemp -d)
mount $device $VM_MOUNT -o loop

# write casper configuration files
cat  > $VM_MOUNT/etc/casper.conf << __END__
# This file should go in /etc/casper.conf
# Supported variables are:
# USERNAME, USERFULLNAME, HOST, BUILD_SYSTEM

export USERNAME="ubuntu"
export USERFULLNAME="Live session user"
export HOST="ubuntu"
export BUILD_SYSTEM="Ubuntu"
__END__

# make squashfs file system from vm image
chmod +w $LIVECD/casper
chmod +w $LIVECD/casper/filesystem.size
mksquashfs $VM_MOUNT $LIVECD/casper/filesystem.squashfs
chmod 444 $LIVECD/casper/filesystem.squashfs

# Add filesystem size
TEMP=$(mktemp)
unsquashfs -lls $LIVECD/casper/filesystem.squashfs | \
grep -v " inodes " | grep -v "unsquashfs:" | \
awk '{print $3}' | grep -v "," > $TEMP
set +x
  for i in `cat $TEMP`
  do
    a=$(($a+$i))
  done
set -x
echo $a > $LIVECD/casper/filesystem.size
  
# build iso
pushd $LIVECD
mkisofs -r -V communtu_classic -cache-inodes -J -l \
        -b isolinux/isolinux.bin -c isolinux/boot.cat \
        -no-emul-boot -boot-load-size 4 -boot-info-table \
        -allow-limited-size -udf -o $OUT .; 
popd

# cleanup
sudo umount $ISOMOUNT
sudo umount $device
sudo kpartx -d $VM_IMG
sudo rm -rf $LIVECD
sudo rm -rf $ISOMOUNR

