#! /bin/sh
eval `cat /etc/lsb-release | grep "DISTRIB_CODENAME="`
echo "**************" >> /var/log/apt-security-updates
date >> /var/log/apt-security-updates
aptitude update >> /var/log/apt-security-updates
aptitude safe-upgrade -o Aptitude::Delete-Unused=false --assume-yes --target-release ${DISTRIB_CODENAME}-security >> /var/log/apt-security-updates
echo "Security updates (if any) installed"  >> /var/log/apt-security-updates 
