#!/usr/bin/ruby

f = File.open(ARGV[0])
outfile = File.open(ARGV[1],"w")

while(!f.eof && (line = f.gets)[0]!="#"[0]) do
  outfile.puts line
end

groups = []
while not f.eof? do
  group = [line]
  while(!f.eof? && (line = f.gets)[0]!="#"[0]) do
    group << line
  end
  groups << group
end

f.close

groups.sort! {|g1,g2| g1[1] <=> g2[1] }
groups.each do |group|
  group.each do |line|
    outfile.puts line
  end
end

outfile.close