#!/usr/bin/ruby
# (c) 2008-2011 byllgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.


f = File.open(ARGV[0])
outfile = File.open(ARGV[1],"w")

while(!f.eof && (line = f.gets)[0]!="#"[0]) do
  outfile.puts line
end

groups = []
while not f.eof? do
  group = [line]
  while(!f.eof? && (line = f.gets)[0]!="#"[0]) do
    group << line
  end
  groups << group
end

f.close

groups.sort! {|g1,g2| g1[1] <=> g2[1] }
groups.each do |group|
  group.each do |line|
    outfile.puts line
  end
end

outfile.close
