#!/bin/bash
sed -i 's/:message_\([0-9]*\), :scope => \[:txt, :\([a-zA-Z]*\), :\([a-zA-Z]*\), :\([a-zA-Z]*\)\]/:\2_\3_\4_\1/g' $1
sed -i 's/:message_\([0-9]*\), :scope => \[:txt, :\([a-zA-Z]*\), :\([a-zA-Z]*\)\]/:\2_\3_\1/g' $1