#!/usr/bin/ruby
y = YAML::load_file(ARGV[0])

# flatten the messages to get shorter IDs
# use 3 and 4 nestings

res = {}
y["some-LAN"]["txt"].each do |key1,val1|
  val1.each do |key2,val2|
    val2.each do |key3,val3|
      if val3.class==Hash then
        val3.each do |key4,val4|
          res[key1+"_"+key2+"_"+key3+"_"+key4.gsub(/message_/,'')] = val4
        end
      else
        res[key1+"_"+key2+"_"+key3.gsub(/message_/,'')] = val3
      end
    end
  end
end; nil

File.open(ARGV[0],"w") do |f|
  YAML::dump({"de" => res}, f)
  f.close
end
