#!/bin/bash
############################
# Author: Timo Denissen    #
# E-Mail: timo@communtu.de #
# Version: 1.4             #
############################

locales_folder=config/locales
source_lang=$1
dest_lang=$2
dest_yml_file=$locales_folder/template-$dest_lang.yml
dest_pot_file=$locales_folder/template-$dest_lang.pot
dest_po_file=$locales_folder/template-$dest_lang.po
source_yml_file=$locales_folder/template-$source_lang.yml

# Check for number of arguments
if [ $# -lt 2 ]; then
    echo "Usage: script/translation source-language translation-language"
    exit 1
fi

# Loading scripts with source_lang and dest_lang
script/yaml2po $source_lang $source_yml_file $dest_pot_file
poedit $dest_po_file
script/po2yaml $dest_lang $dest_po_file $dest_yml_file
script/yaml2po $dest_lang $dest_yml_file $dest_pot_file
echo "Run 'svn ci' for folder $locales_folder"