#!/bin/bash

echo "do not use this script. It breaks the french and english pages due to [2029]. First fix #1286"
exit 1

############################
# Author: Timo Denissen    #
# E-Mail: timo@communtu.de #
# Version: 1.1             #
############################
script/yaml2po de config/locales/template.yml config/locales/template.pot
poedit config/locales/template.po
script/po2yaml config/locales/template.po config/locales/template-en.yml
script/yaml2po en config/locales/template-en.yml config/locales/template-en.pot
echo 'Run "svn ci" for folder "config/locales"'
