#!/bin/bash
############################
# Author: Timo Denissen    #
# E-Mail: timo@communtu.de #
# Version: 1.1             #
############################


# (c) 2008-2011 by Allgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.

script/yaml2po de config/locales/template-de.yml config/locales/template-fr.pot
poedit config/locales/template-fr.po
script/po2yaml fr config/locales/template-fr.po config/locales/template-fr.yml
#script/yaml2po en config/locales/template-fr.yml config/locales/template-fr.pot
echo 'Run "git commit -a" for folder "config/locales"'
