#!/bin/bash

# (c) 2008-2011 byllgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.

function start {
     echo "Starting mongrels server at port $1"
     nohup script/server -e production -p $1 >> log/server$1.log 2>&1 &
}

function startall {
  for port in $(cat config/ports); do
    start $port
  done
}

function stop {
    echo "Stopping mongrels server at port $1"
	pkill -2 -f "\-p $1"
}

function stopall {
  for port in $(cat config/ports); do
    stop $port
  done
}

function restartall {
  for port in $(cat config/ports); do
    stop $port
    start $port
  done
}

# main script

if [ `whoami` == root ]; then
  echo "This script must not be run as root."
  exit 1
fi
cd $(dirname $0)/..

case $1 in
	start)
		startall
	;;
	stop)
		stopall

	;;
	restart)
		restartall
	;;

esac
