#!/usr/bin/ruby
# (c) 2008-2011 by Allgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.

require 'yaml.rb'


def quote s
  if s.nil?
    return nil
  end
  s.gsub(/"/,'\\\"').gsub(/\n/,'\\\n')
end

if ARGV.size < 3 then
  puts "usage: yaml2po language-code source-file target-file"
else
y = YAML::load_file(ARGV[1])

f = File.open(ARGV[2],"w")

f.puts 'msgid ""'
f.puts 'msgstr ""'
f.puts '"Plural-Forms: n != 1\n"'
f.puts '"Project-Id-Version: test 0.1\n"'
f.puts '"POT-Creation-Date: \n"'
f.puts '"PO-Revision-Date: \n"'
f.puts '"Last-Translator: Timo Denissen <timo-denissen@gmx.de>\n"'
f.puts '"Language-Team: Communtu <info@communtu.de>\n"'
f.puts '"MIME-Version: 1.0\n"'
f.puts '"Content-Type: text/plain; charset=utf-8\n"'
f.puts '"Content-Transfer-Encoding: 8bit\n"'
f.puts '"X-Poedit-Language: German\n"'
f.puts '"X-Poedit-Country: GERMANY\n"'
f.puts '"X-Poedit-SourceCharset: utf-8\n"'
f.puts ""

# use German localisaiton
y[ARGV[0]].to_a.each do |tag_msg|
  tag = tag_msg[0]
  msg = tag_msg[1]
  f.puts "#: #{tag}"
  f.puts "msgid \"#{quote(msg)}\""
  f.puts 'msgstr ""'

end
f.close
end
