#!/usr/bin/ruby

require 'yaml.rb'

y = YAML::load_file(ARGV[0])

f = File.open(ARGV[1],"w")

f.puts 'msgid ""'
f.puts 'msgstr ""'
f.puts '"Plural-Forms: n != 1\n"'
f.puts '"Project-Id-Version: test 0.1\n"'
f.puts '"POT-Creation-Date: \n"'
f.puts '"PO-Revision-Date: \n"'
f.puts '"Last-Translator: Timo Denissen <timo-denissen@gmx.de>\n"'
f.puts '"Language-Team: Communtu <info@communtu.de>\n"'
f.puts '"MIME-Version: 1.0\n"'
f.puts '"Content-Type: text/plain; charset=utf-8\n"'
f.puts '"Content-Transfer-Encoding: 8bit\n"'
f.puts '"X-Poedit-Language: German\n"'
f.puts '"X-Poedit-Country: GERMANY\n"'
f.puts '"X-Poedit-SourceCharset: utf-8\n"'
f.puts ""

# use German localisaiton
y["de"].to_a.sort.each do |tag_msg|
  tag = tag_msg[0]
  msg = tag_msg[1]
  f.puts "#: #{tag}"
  f.puts "msgid \"#{msg}\""
  f.puts 'msgstr ""'

end
f.close
