#!/bin/bash

# make a copy of a kvm image that is filled with zeroes for unused blocks

# (c) 2008-2011 byllgemeinbildung e.V., Bremen, Germany
# This file is part of Communtu.

# Communtu is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Communtu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero Public License for more details.

# You should have received a copy of the GNU Affero Public License
# along with Communtu.  If not, see <http://www.gnu.org/licenses/>.


infile=$1
outfile=$1.zero

# copy old file
cp $infile $outfile

# make devices for partitions
kpartx_in=$(sudo kpartx -av $infile)
loopin1=$(echo $kpartx_in  | cut -d " " -f 3)
kpartx_out=$(sudo kpartx -av $outfile)
loopout1=$(echo $kpartx_out  | cut -d " " -f 3)
loopout2=$(echo $kpartx_out  | cut -d " " -f 21)

# fill new partitions with zeros
sudo dd if=/dev/zero of=/dev/mapper/$loopout1
sudo dd if=/dev/zero of=/dev/mapper/$loopout2

# make file system and copy files from old to new partition
sudo mkfs -t ext3 /dev/mapper/$loopout1
sudo mount /dev/mapper/$loopin1 /mnt2
sudo mount /dev/mapper/$loopout1 /mnt3
sudo rm -r /mnt3/lost+found
sudo rsync -a /mnt2/* /mnt3/
sudo umount /mnt2
sudo umount /mnt3

# remove devices for partitions
sudo kpartx -d $infile
sudo kpartx -d $outfile

qemu-img convert -O qcow2 $outfile $outfile.qcow