#!/bin/bash

# make a copy of a kvm image that is filled with zeroes for unused blocks

infile=$1
outfile=$1.zero

# copy old file
cp $infile $outfile

# make devices for partitions
kpartx_in=$(sudo kpartx -av $infile)
loopin1=$(echo $kpartx_in  | cut -d " " -f 3)
kpartx_out=$(sudo kpartx -av $outfile)
loopout1=$(echo $kpartx_out  | cut -d " " -f 3)
loopout2=$(echo $kpartx_out  | cut -d " " -f 21)

# fill new partitions with zeros
sudo dd if=/dev/zero of=/dev/mapper/$loopout1
sudo dd if=/dev/zero of=/dev/mapper/$loopout2

# make file system and copy files from old to new partition
sudo mkfs -t ext3 /dev/mapper/$loopout1
sudo mount /dev/mapper/$loopin1 /mnt2
sudo mount /dev/mapper/$loopout1 /mnt3
sudo rm -r /mnt3/lost+found
sudo rsync -a /mnt2/* /mnt3/
sudo umount /mnt2
sudo umount /mnt3

# remove devices for partitions
sudo kpartx -d $infile
sudo kpartx -d $outfile

qemu-img convert -O qcow2 $outfile $outfile.qcow